/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CalendarEvent {
  'id' : bigint,
  'owner' : Principal,
  'date' : string,
  'name' : string,
  'eventType' : EventType,
}
export type Category = { 'accessories' : null } |
  { 'tops' : null } |
  { 'bottoms' : null } |
  { 'shoes' : null } |
  { 'outerwear' : null };
export interface ClothingItem {
  'id' : bigint,
  'seasons' : Array<Season>,
  'owner' : Principal,
  'name' : string,
  'color' : string,
  'category' : Category,
  'photo' : ExternalBlob,
  'wearCount' : bigint,
  'lastWorn' : [] | [bigint],
  'styleTags' : Array<string>,
}
export type EventType = { 'work' : null } |
  { 'sport' : null } |
  { 'casual' : null } |
  { 'formal' : null };
export type ExternalBlob = Uint8Array;
export type Season = { 'fall' : null } |
  { 'winter' : null } |
  { 'summer' : null } |
  { 'spring' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCalendarEvent' : ActorMethod<[string, string, EventType], bigint>,
  'createClothingItem' : ActorMethod<
    [string, Category, string, Array<string>, Array<Season>, ExternalBlob],
    bigint
  >,
  'getCalendarEvents' : ActorMethod<[], Array<CalendarEvent>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClothingItems' : ActorMethod<[], Array<ClothingItem>>,
  'getOutfitSuggestion' : ActorMethod<[bigint, EventType], Array<ClothingItem>>,
  'getSustainabilityReport' : ActorMethod<[], Array<ClothingItem>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeather' : ActorMethod<[number, number], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logWear' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'testWearCycle' : ActorMethod<[bigint], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];