/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EventType = IDL.Variant({
  'work' : IDL.Null,
  'sport' : IDL.Null,
  'casual' : IDL.Null,
  'formal' : IDL.Null,
});
export const Category = IDL.Variant({
  'accessories' : IDL.Null,
  'tops' : IDL.Null,
  'bottoms' : IDL.Null,
  'shoes' : IDL.Null,
  'outerwear' : IDL.Null,
});
export const Season = IDL.Variant({
  'fall' : IDL.Null,
  'winter' : IDL.Null,
  'summer' : IDL.Null,
  'spring' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CalendarEvent = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'eventType' : EventType,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ClothingItem = IDL.Record({
  'id' : IDL.Nat,
  'seasons' : IDL.Vec(Season),
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'category' : Category,
  'photo' : ExternalBlob,
  'wearCount' : IDL.Nat,
  'lastWorn' : IDL.Opt(IDL.Int),
  'styleTags' : IDL.Vec(IDL.Text),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCalendarEvent' : IDL.Func(
      [IDL.Text, IDL.Text, EventType],
      [IDL.Nat],
      [],
    ),
  'createClothingItem' : IDL.Func(
      [
        IDL.Text,
        Category,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(Season),
        ExternalBlob,
      ],
      [IDL.Nat],
      [],
    ),
  'getCalendarEvents' : IDL.Func([], [IDL.Vec(CalendarEvent)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClothingItems' : IDL.Func([], [IDL.Vec(ClothingItem)], ['query']),
  'getOutfitSuggestion' : IDL.Func(
      [IDL.Nat, EventType],
      [IDL.Vec(ClothingItem)],
      ['query'],
    ),
  'getSustainabilityReport' : IDL.Func([], [IDL.Vec(ClothingItem)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeather' : IDL.Func([IDL.Float64, IDL.Float64], [IDL.Text], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logWear' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'testWearCycle' : IDL.Func([IDL.Nat], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EventType = IDL.Variant({
    'work' : IDL.Null,
    'sport' : IDL.Null,
    'casual' : IDL.Null,
    'formal' : IDL.Null,
  });
  const Category = IDL.Variant({
    'accessories' : IDL.Null,
    'tops' : IDL.Null,
    'bottoms' : IDL.Null,
    'shoes' : IDL.Null,
    'outerwear' : IDL.Null,
  });
  const Season = IDL.Variant({
    'fall' : IDL.Null,
    'winter' : IDL.Null,
    'summer' : IDL.Null,
    'spring' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CalendarEvent = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'eventType' : EventType,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ClothingItem = IDL.Record({
    'id' : IDL.Nat,
    'seasons' : IDL.Vec(Season),
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'category' : Category,
    'photo' : ExternalBlob,
    'wearCount' : IDL.Nat,
    'lastWorn' : IDL.Opt(IDL.Int),
    'styleTags' : IDL.Vec(IDL.Text),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCalendarEvent' : IDL.Func(
        [IDL.Text, IDL.Text, EventType],
        [IDL.Nat],
        [],
      ),
    'createClothingItem' : IDL.Func(
        [
          IDL.Text,
          Category,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(Season),
          ExternalBlob,
        ],
        [IDL.Nat],
        [],
      ),
    'getCalendarEvents' : IDL.Func([], [IDL.Vec(CalendarEvent)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClothingItems' : IDL.Func([], [IDL.Vec(ClothingItem)], ['query']),
    'getOutfitSuggestion' : IDL.Func(
        [IDL.Nat, EventType],
        [IDL.Vec(ClothingItem)],
        ['query'],
      ),
    'getSustainabilityReport' : IDL.Func(
        [],
        [IDL.Vec(ClothingItem)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeather' : IDL.Func([IDL.Float64, IDL.Float64], [IDL.Text], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logWear' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'testWearCycle' : IDL.Func([IDL.Nat], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };